#http://thornelabs.net/2014/03/08/install-ansible-create-your-inventory-file-and-run-an-ansible-playbook-and-some-ansible-commands.html

#http://thornelabs.net/2014/02/03/hash-roots-password-in-rhel-and-centos-kickstart-profiles.html

---

- name: configure cloudgenius user
  hosts: all
  become: yes
  gather_facts: False

  vars:
    # created with: openssl passwd -1 "cloudgenius"
    cloudgenius_password: $1$pJtIwMjJ$0D5BUs/T7QbUjmc5yCp81/

  tasks:

    - name: Add user cloudgenius
      user: name=cloudgenius password={{cloudgenius_password}} shell=/bin/bash groups=root append=yes

    - name: Add user cloudgenius to sudoers
      lineinfile:
        "dest=/etc/sudoers
        regexp='^cloudgenius ALL'
        line='cloudgenius ALL=(ALL) NOPASSWD: ALL'
        state=present"

    # Using with_file
    - name: Set up authorized_keys for the cloudgenius user
      authorized_key: user=cloudgenius key="{{ item }}"
      with_file:
        - public_keys/alex_macbookpro.pub

    - name: Disallow root SSH access
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PermitRootLogin"
        line="PermitRootLogin no"
        state=present
      notify:
        - restart ssh

    - name: Disallow SSH password authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^PasswordAuthentication"
        line="PasswordAuthentication no"
        state=present
      notify:
        - restart ssh

    - name: Disallow SSH GSS API authentication
      lineinfile:
        dest=/etc/ssh/sshd_config
        regexp="^GSSAPIAuthentication"
        line="GSSAPIAuthentication no"
        state=present
      notify:
        - restart ssh

  handlers:
  - name: restart ssh
    service:
      name=ssh
      state=restarted
